(in-package #:arrow-protocol)

;;; Parquet hybrid RLE / bit-packing (levels + dictionary indices).

(defun %bit-width (max-value)
  (if (zerop max-value)
      0
      (integer-length max-value)))

(defun %put-uvarint (out pos n)
  (let ((p pos))
    (loop
      (let ((b (logand n #x7f)))
        (setf n (ash n -7))
        (when (plusp n) (setf b (logior b #x80)))
        (vector-push-extend b out)
        (incf p)
        (when (zerop n)
          (return p))))))

(defun %uvarint-at (buf pos)
  (let ((n 0)
        (shift 0)
        (p pos))
    (loop
      (let ((b (aref buf p)))
        (incf p)
        (setf n (logior n (ash (logand b #x7f) shift)))
        (incf shift 7)
        (when (zerop (logand b #x80))
          (return (values n p)))))))

(defun %pack-bits (values bit-width)
  (if (zerop bit-width)
      (make-array 0 :element-type '(unsigned-byte 8))
      (let* ((n (length values))
             (nbytes (ceiling (* n bit-width) 8))
             (out (make-array nbytes :element-type '(unsigned-byte 8) :initial-element 0))
             (bit 0))
        (loop for v across (if (vectorp values) values (coerce values 'vector))
              do (loop for k from 0 below bit-width
                       when (logbitp k v)
                         do (let ((byte (ash bit -3))
                                  (off (ldb (byte 3 0) bit)))
                              (setf (aref out byte)
                                    (logior (aref out byte) (ash 1 off))))
                       do (incf bit)))
        out)))

(defun %unpack-bits (buf start nbytes bit-width count)
  (let ((out (make-array count))
        (bit 0))
    (loop for i from 0 below count
          do (let ((v 0))
               (loop for k from 0 below bit-width
                     do (let ((byte (ash bit -3))
                              (off (ldb (byte 3 0) bit)))
                          (when (and (< byte nbytes)
                                     (plusp (logand (aref buf (+ start byte))
                                                    (ash 1 off))))
                            (setf v (logior v (ash 1 k)))))
                        (incf bit))
               (setf (aref out i) v)))
    out))

(defun encode-hybrid-rle (values bit-width)
  "Hybrid RLE/bit-packing without a 4-byte length prefix."
  (let* ((vals (coerce values 'vector))
         (n (length vals))
         (out (make-array (max 16 (* n 2)) :element-type '(unsigned-byte 8)
                          :adjustable t :fill-pointer 0))
         (i 0))
    (when (zerop n)
      (return-from encode-hybrid-rle
        (make-array 0 :element-type '(unsigned-byte 8))))
    (loop while (< i n)
          do (let ((run 1)
                   (v (aref vals i)))
               (loop while (and (< (+ i run) n)
                                (eql (aref vals (+ i run)) v))
                     do (incf run))
               (if (and (>= run 8) (plusp bit-width))
                   (progn
                     (%put-uvarint out (length out) (ash run 1))
                     (let ((nbytes (ceiling bit-width 8)))
                       (loop for k from 0 below nbytes
                             do (vector-push-extend (ldb (byte 8 (* k 8)) v) out)))
                     (incf i run))
                   (let* ((take (min (* 8 (ceiling (min (- n i) (max run 8)) 8))
                                     (* 8 (ceiling (- n i) 8))))
                          (chunk (subseq vals i (min n (+ i take))))
                          (padded (if (= (length chunk) take)
                                      chunk
                                      (let ((p (make-array take :initial-element 0)))
                                        (replace p chunk)
                                        p))))
                     (setf take (length padded))
                     (%put-uvarint out (length out) (logior (ash (/ take 8) 1) 1))
                     (let ((packed (%pack-bits padded bit-width)))
                       (loop for b across packed do (vector-push-extend b out)))
                     (incf i take)))))
    (let ((fixed (make-array (length out) :element-type '(unsigned-byte 8))))
      (replace fixed out)
      fixed)))

(defun encode-rle-levels (levels max-level)
  "Data-page v1 level stream: 4-byte LE length + hybrid RLE."
  (if (zerop max-level)
      (make-array 0 :element-type '(unsigned-byte 8))
      (let* ((bw (max 1 (%bit-width max-level)))
             (payload (encode-hybrid-rle levels bw))
             (out (make-array (+ 4 (length payload)) :element-type '(unsigned-byte 8))))
        (loop for i from 0 below 4
              do (setf (aref out i) (ldb (byte 8 (* i 8)) (length payload))))
        (replace out payload :start1 4)
        out)))

(defun decode-hybrid-rle (buf start end bit-width count)
  (let ((out (make-array count))
        (i 0)
        (p start))
    (loop while (and (< i count) (< p end))
          do (multiple-value-bind (header np) (%uvarint-at buf p)
               (setf p np)
               (if (plusp (logand header 1))
                   (let* ((groups (ash header -1))
                          (nvals (* groups 8))
                          (nbytes (ceiling (* nvals bit-width) 8))
                          (chunk (%unpack-bits buf p nbytes bit-width nvals)))
                     (incf p nbytes)
                     (loop for j from 0 below nvals
                           while (< i count)
                           do (setf (aref out i) (aref chunk j))
                              (incf i)))
                   (let* ((run (ash header -1))
                          (nbytes (max 1 (ceiling bit-width 8)))
                          (v 0))
                     (loop for k from 0 below nbytes
                           do (setf v (logior v (ash (aref buf p) (* k 8))))
                              (incf p))
                     (loop repeat run
                           while (< i count)
                           do (setf (aref out i) v)
                              (incf i))))))
    (values out p)))

(defun decode-rle-levels (buf start max-level count)
  "Read a 4-byte-length-prefixed hybrid RLE level stream.
   → (values levels next-pos)"
  (if (zerop max-level)
      (values (make-array count :initial-element 0) start)
      (let* ((len (logior (aref buf start)
                          (ash (aref buf (1+ start)) 8)
                          (ash (aref buf (+ start 2)) 16)
                          (ash (aref buf (+ start 3)) 24)))
             (payload-start (+ start 4))
             (bw (max 1 (%bit-width max-level))))
        (multiple-value-bind (levels pos)
            (decode-hybrid-rle buf payload-start (+ payload-start len) bw count)
          (declare (ignore pos))
          (values levels (+ payload-start len))))))

(defun encode-rle-dictionary (indices bit-width)
  "RLE_DICTIONARY values: 1-byte bitwidth + hybrid RLE."
  (let* ((payload (encode-hybrid-rle indices (max 1 bit-width)))
         (out (make-array (1+ (length payload)) :element-type '(unsigned-byte 8))))
    (setf (aref out 0) (max 1 bit-width))
    (replace out payload :start1 1)
    out))

(defun decode-rle-dictionary (buf start end count)
  (let ((bw (aref buf start)))
    (decode-hybrid-rle buf (1+ start) end bw count)))

(defun encode-bit-packed-levels (levels bit-width)
  (%pack-bits (coerce levels 'vector) bit-width))

(defun decode-bit-packed-levels (buf start nbytes bit-width count)
  (%unpack-bits buf start nbytes bit-width count))
